name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        go: ["1.21.11", "1.22.4"]
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go }}

      - name: go mod download
        env:
          CGO_ENABLED: 0
        run: |
          go mod download

      - name: go test
        env:
          CGO_ENABLED: 0
        run: |
          go test $(go list ./... | grep -v /e2e)

      - name: go test -race
        env:
          CGO_ENABLED: 1
        run: |
          go test -race $(go list ./... | grep -v /e2e)
