name: Nix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake-check:
    name: flake check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ab6bcb2d5af0e904d04aea750e2089e9dc4cbfdd # v13

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@b46e247b898aa56e6d2d2e728dc6df6c84fdb738 # v7

      - name: nix flake check
        run: nix flake check --all-systems
